### PR TITLE
JCRVLT-587 check for duplicate jcr:uuid property values

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by kwin** [comment]
@reschke Can you test this change with some affected packages?

**Comment by reschke** [comment]
Not familiar with the validator. How would I test that?

**Comment by kwin** [comment]
With the Maven plugin leveraging the SNAPSHOT version of the validator in its dependencies: https://jackrabbit.apache.org/filevault-package-maven-plugin/validate-package-mojo.html

**Comment by reschke** [comment]
so do I need to build a new snapshot release of the maven plugin, or is there a shortcut than I can take?

**Comment by kwin** [comment]
No need to rebuild the Maven plugin, just declare the following in your pom.xml (and have the most recent SNAPSHOT build of FileVault validation in your Maven repo
```
<plugin>
                    <groupId>org.apache.jackrabbit</groupId>
                    <artifactId>filevault-package-maven-plugin</artifactId>
                   <version>1.2.2</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.apache.jackrabbit.vault</groupId>
                            <artifactId>vault-validation</artifactId>
                            <version>3.5.9-SNAPSHOT</version>
                        </dependency>
                    </dependencies>
                </plugin>
```

**Comment by reschke** [comment]
That assumes that I actually have a project that *builds* the package I want to validatre, right? (All I have is an existing ZIP file from a customer system...).

**Review by reschke — APPROVED** [review]
I didn't check the code, but I can confirm that the new validator complains for several nodes with duplicate jcd:uuids in my test package.

**Pull request merged**
