### PR TITLE
JCRVLT-673: AggregateImpl: do not collect & sort nodes that will be s…

### PR DESCRIPTION
**Pull request by reschke**
…kipped anyway

### CODE REVIEW

**Comment by reschke** [comment]
@kwin - this passes tests, and it has shown a good improvement in out production use case. Could you please review?

**Comment by kwin** [comment]
@reschke Can you rebase to make the ASF Jenkins build succeed?

**Comment by reschke** [comment]
Done.

**Review by kwin — APPROVED** [review]
LGTM, although not really familiar with that code section.

**Comment by reschke** [comment]
OK - I'll go ahead then.

**Pull request merged**
