### PR TITLE
Changing log level from error to info in case of jar file doesn't con…

### PR DESCRIPTION
**Pull request by nit23uec**
…tains jcr_root

@trivial
cc @tripodsan

### CODE REVIEW

**Comment by tripodsan** [comment]
can you give a reason why this change is good? as a user of the API, I would expect the appropriate error message shown if I upload a wrong package.

please open a jira ticket, if you still think this change is required.

**Comment by nit23uec** [comment]
@tripodsan the jar file could contain some native components as well (c/c++ components compiled for specific platforms and in this case, they would not be OSGI bundles). They are meant to be processes using c custom resource transformer rather than a PackageTransformer which call jackrabbit layer. Also, the PackageTransformer gives info in the logs rather than the error which seems to be inconsistent with the jackrabbit layer logging.

**Comment by nit23uec** [comment]
created https://issues.apache.org/jira/browse/JCRVLT-267

**Comment by tripodsan** [comment]
this comment is not related to this apache project. please keep the communication channels clear.

From the point of this API, the package manager doesn't know about PackageTransformer, or potentially uploaded OSGi bundles. All it knows is, that it receives a stream that is not a package and therefore logs an error.

**Comment by nit23uec** [comment]
Thanks for the guidance @tripodsan . I'm closing this PR.

**Pull request closed without merging**
